banking:
  outputs:
    dev:
      account: YDLXZSZ-HAC92562
      database: banking
      password: Killamsettim@nohar1996
      role: accountadmin
      schema: analytics
      threads: 4
      type: snowflake
      user: MANOHAR
      warehouse: COMPUTE_WH
  target: dev
